### ISSUE TITLE
Segfault using 'around' with Timecop on Ruby 2.2.2

### ISSUE THREAD

**Issue by jcoglan** [rspec/rspec-dev#120] opened 2015-04-15 13:34 UTC
I'm not sure if this is a Timecop, RSpec or Ruby issue, but the smallest test case I can write requires the use of `around`. Turning the `around` into statements inside the `it` block doesn't cause a segfault.

https://github.com/travisjeffery/timecop/issues/150

**Comment by jcoglan** [comment] 2015-04-15 15:14
I've also [reported this issue to Ruby](https://bugs.ruby-lang.org/issues/11071), so if it's not RSpec's fault feel free to close this and refer others to that issue.

**Comment by myronmarston** [comment] 2015-04-15 15:19
Thanks for reporting it upstream.  It's definitely a bug in Ruby -- programs that use no c-extensions should by definition not segfault, and when they do, it's a ruby bug.  In this case, it looks like a regression in 2.2.  I can repro the segfault there but not on 2.1.

In addition, there's a pretty simple work around:

``` ruby
  around do |example|
    Timecop.travel(Time.parse('2015-01-01 06:30:00')) { example.run }
  end
```

The `example` object defines a `to_proc` specifically so that you can pass it as `&example` (as you were) but if you just put `example.run` in a block yourself it avoids the issue.  No idea why, but there's clearly some weirdness going on in the ruby VM.

Closing since there's nothing for us to do here as far as I can see.

**Closed by myronmarston** 2015-04-15 15:19 UTC
